streams:
  - name: text_stream
    handlers:
      - type: text_handler
      - type: agent_handler
      - type: forwarding_handler
        target: analytics_stream
    connections:
      - target: analytics_stream

  - name: image_stream
    handlers:
      - type: image_handler
      - type: agent_handler
    connections: []

  - name: analytics_stream
    handlers:
      - type: agent_handler
    connections: []

agents:
  - name: Agent1
    category: "AssistAgent"
    llm_type: "qwen"
    subscribed_streams:
      - text_stream
      - image_stream

  - name: Agent2
    category: "AssistAgent"
    llm_type: "qwen"
    subscribed_streams:
      - text_stream

  - name: Agent3
    category: "AssistAgent"
    llm_type: "qwen"
    subscribed_streams:
      - analytics_stream
